### ISSUE TITLE
Plugin incompatibility with version 2.10.1

### ISSUE THREAD

**Issue by cuadragg** [polca/ScenarioLink#42]
Hi, Marc

I realized that you are working on fixing this issue. I was wondering if there is already a solution for that? If so, I would highly appreciate it if you could please share it.

Thanks,
Glenda

**Comment by marc-vdm** [comment]
Hi Glenda, 

The solution in #42 should solve your problem. Right now, Activity Browser `2.10.x` and Scenario Link are not compatible yet. We are moving a bit slow due to the summer break. Once we release the new version of Scenario Link that is compatible with Activity Browser `2.10.1` this issue will be closed, which you will receive an email for, thanks for your patience!

-Marc
