### ISSUE TITLE
Question about supported versions of the database

### ISSUE THREAD

**Issue by OliverLyon** [polca/ScenarioLink#47]
In the scenariolink page, I can see the source database of ei 3.9.1 and ei 3.10 (cutoff and consequential). Does it mean it is only compatible with these two versions of the database? Or can I use 3.7 and 3.8 as well? Thanks

**Comment by marc-vdm** [comment]
> Does it mean it is only compatible with these two versions of the database?

Yes, we keep the list small so it's still manageable to find the data you need. You can generate your own databases with Premise though. Or maybe if @romainsacchi has time, he can add the dataset you need -if you let us know which one-.

**Comment by romainsacchi** [comment]
Hi @OliverLyon,

I think we will only keep the options for ecoinvent 3.9 and 3.10, as @marc-vdm said, to keep them manageable.
Also, we already have a design issue now because of the list length (when selecting a scenario, the second window disappears; see https://github.com/polca/ScenarioLink/issues/46).
